version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/src
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    working_dir: /app/src
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 