FROM python:3.11-slim

WORKDIR /app/src

COPY requirements.txt /app/src/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app/src

ENV PYTHONPATH=/app/src

CMD ["python", "-m", "bot.main"] 