FROM python:3.11-slim

WORKDIR /app/src

COPY requirements.txt /app/src/
RUN pip install --no-cache-dir -r requirements.txt

# копируем весь код
COPY ./src /app/src

# дублируем messages.yaml в вложенную папку, которую ждёт код
RUN mkdir -p /app/src/bot/bot \
 && cp /app/src/bot/messages.yaml /app/src/bot/bot/messages.yaml

ENV PYTHONPATH=/app/src

CMD ["python", "-m", "bot.main"]
